"use client";

import { useEffect, useRef, useState } from "react";

export function CommunityMap({ center, name, buildings }: { center: [number, number]; name: string; buildings: number }) {
  const ref = useRef<HTMLDivElement>(null); const [fallback, setFallback] = useState(false);
  useEffect(() => { let map: import("maplibre-gl").Map | undefined; let cancelled = false; import("maplibre-gl").then((maplibregl) => { if (cancelled || !ref.current) return; try { const localMap = new maplibregl.Map({ container: ref.current, center, zoom: 14.2, attributionControl: false, style: { version: 8, sources: {}, layers: [{ id: "background", type: "background", paint: { "background-color": "#e8ece8" } }] } }); map = localMap; localMap.on("load", () => { const [lng, lat] = center; const features = Array.from({ length: Math.min(buildings, 12) }, (_, index) => { const dx = ((index % 4) - 1.5) * 0.0015; const dy = (Math.floor(index / 4) - 1) * 0.0013; return { type: "Feature" as const, properties: { label: `Building ${index + 1}` }, geometry: { type: "Polygon" as const, coordinates: [[[lng + dx - .00045, lat + dy - .00025], [lng + dx + .00045, lat + dy - .00025], [lng + dx + .00045, lat + dy + .00025], [lng + dx - .00045, lat + dy + .00025], [lng + dx - .00045, lat + dy - .00025]]] } }; }); localMap.addSource("buildings", { type: "geojson", data: { type: "FeatureCollection", features } }); localMap.addLayer({ id: "building-fill", type: "fill", source: "buildings", paint: { "fill-color": "#166765", "fill-opacity": .72 } }); localMap.addLayer({ id: "building-outline", type: "line", source: "buildings", paint: { "line-color": "#0d3b3a", "line-width": 1 } }); }); } catch { setFallback(true); } }).catch(() => setFallback(true)); return () => { cancelled = true; map?.remove(); }; }, [center, buildings]);
  return <div className={`map-wrap ${fallback ? "map-fallback" : ""}`}><div ref={ref} className="map-canvas" aria-label={`Token-free property map for ${name}`}/><div className="map-label"><span/>Local GeoJSON · no external tiles</div>{fallback && <div className="map-static"><strong>{name}</strong><span>{buildings} building footprints</span></div>}</div>;
}
