"use client";

import { AlertTriangle, ArchiveRestore, BadgeCheck, CheckCircle2, Clock3, FileCheck2, FileKey2, Fingerprint, Inbox, KeyRound, LoaderCircle, LockKeyhole, MessageSquareText, RefreshCw, Send, ShieldAlert, ShieldCheck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";

type Scenario = "blocked" | "confirmed" | "delivered" | "clarification" | "accepted" | "corrected" | "pending" | "revoked";
type Tab = "submission" | "reviewer" | "decisions" | "maintenance";
type Workspace = {
  bindings: Array<Record<string, unknown>>;
  deliveries: Array<Record<string, unknown>>;
  receipts: Array<Record<string, unknown>>;
  sessions: Array<Record<string, unknown>>;
  requests: Array<Record<string, unknown>>;
  requestResponses: Array<Record<string, unknown>>;
  outcomes: { evidence: Array<Record<string, unknown>>; model: Array<Record<string, unknown>>; rating: Array<Record<string, unknown>>; underwriting: Array<Record<string, unknown>>; placement: Array<Record<string, unknown>>; funding: Array<Record<string, unknown>> };
  closures: Array<Record<string, unknown>>;
  rollForwards: Array<Record<string, unknown>>;
};

const fixture: Workspace = {
  bindings: [{ id: "binding-fixture", submissionVersionId: "submission-v3", playbookVersionId: "playbook-cal-wui-v6", profileVersionId: "profile-community-v4", commitmentVersionId: "review-commitment-v2", requestedAction: "Review evidence package and return an evidence disposition", destinationLabel: "Fictional Sierra Mutual · property review desk", deliveryMethod: "secure_review_link", readinessStatus: "ready_with_caveats", blockerSnapshot: [], caveatSnapshot: ["Tree-spacing evidence covers the surveyed common area only.", "Review commitment is review-only and does not imply terms, price, capacity, or renewal."], preparedBy: "broker@fixture.test", preparedAt: "2026-12-12T18:10:00.000Z", humanConfirmed: true }],
  deliveries: [{ id: "delivery-2", submissionVersionId: "submission-v3", attemptNumber: 2, status: "delivered", destination: "review-desk@fictional.test", providerKey: "deterministic-offline-custody", providerReference: "fixture-51f0c1a98e11821a", requestHash: "3e7b3f5f31a7188104abcde36ef8b0495820fe0084b8dca380cd9e3e5c922fa1", attemptedAt: "2026-12-12T18:20:00.000Z", deliveredAt: "2026-12-12T18:20:00.000Z" }, { id: "delivery-1", submissionVersionId: "submission-v3", attemptNumber: 1, status: "failed", destination: "review-desk@fictional.test", providerKey: "unavailable-provider", failureCode: "provider_unavailable", attemptedAt: "2026-12-12T18:15:00.000Z" }],
  receipts: [{ id: "receipt-fixture", deliveryId: "delivery-2", receiptType: "review_link_created", receiptHash: "bc8f568099f09efac0af0a75b39861f02b80de228153b44e37b76614b860b085", sourceAuthority: "Fortify deterministic offline delivery fixture", sourceReference: "fixture://51f0c1a98e11821a", receivedAt: "2026-12-12T18:20:00.000Z", humanConfirmed: true }],
  sessions: [{ id: "review-session-fixture", submissionVersionId: "submission-v3", status: "active", expiresAt: "2026-12-19T18:20:00.000Z", downloadAllowed: false, allowedActions: ["submission:read", "reviewer_request:create", "evidence_acceptance_event:create"] }],
  requests: [{ id: "request-fixture", reviewerSessionId: "review-session-fixture", requestType: "clarification", originalLanguage: "Please identify which roof photographs show Buildings 4 and 5 and confirm their capture dates.", normalizedReason: "scope_clarification", status: "responded", requestedAt: "2026-12-13T16:05:00.000Z" }],
  requestResponses: [{ id: "response-fixture", reviewerRequestId: "request-fixture", originalLanguage: "Exhibits E07 and E08 are labeled by building and retain the original device capture dates.", evidenceVersionIds: ["evidence-roof-e07-v2", "evidence-roof-e08-v1"], respondedAt: "2026-12-13T18:25:00.000Z", humanConfirmed: true }],
  outcomes: {
    evidence: [{ id: "evidence-event-2", evidenceVersionId: "evidence-roof-e07-v2", disposition: "accepted", originalLanguage: "Roof documentation accepted for the stated buildings.", normalizedReason: "scope_confirmed", sourceAuthority: "Fictional Sierra Mutual", sourceReference: "FSM-RESP-4402", supersedesEventId: "evidence-event-1" }],
    model: [{ id: "model-event-1", mappingId: "mapping-roof-v2", disposition: "input_modified", originalLanguage: "Input accepted with the qualifier 'documented common-area buildings only'.", normalizedReason: "scope_narrowed", acceptedValue: { value: "Class A documented — common-area buildings only" } }],
    rating: [{ id: "rating-event-1", disposition: "unknown", originalLanguage: "No rating determination was included in this response.", normalizedReason: "no_rating_response" }],
    underwriting: [{ id: "uw-event-1", disposition: "quote_review_initiated", originalLanguage: "The evidence package has been routed for fictional quote review.", normalizedReason: "review_initiated" }],
    placement: [], funding: [],
  },
  closures: [{ id: "closure-fixture", closureStatus: "closed_outcome_pending", unresolvedCaveats: ["Rating treatment not provided", "Placement response pending"], note: "Evidence review cycle closed; downstream outcomes remain explicitly pending." }],
  rollForwards: [{ id: "roll-forward-fixture", status: "review_required", basis: "Annual roof-image refresh is due before the next renewal evidence cycle." }],
};

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const shortened = (value: unknown) => String(value ?? "Unavailable").slice(0, 12);

export function MarketRecognitionWorkspace({ mode }: { mode: "sandbox" | "production" }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(mode === "sandbox" ? fixture : null);
  const [status, setStatus] = useState<"loading" | "ready" | "error">(mode === "sandbox" ? "ready" : "loading");
  const [scenario, setScenario] = useState<Scenario>("clarification");
  const [tab, setTab] = useState<Tab>("submission");
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [notice, setNotice] = useState("");
  useEffect(() => {
    if (mode !== "production") return;
    const controller = new AbortController();
    fetch("/api/production/recognition/workspace", { cache: "no-store", signal: controller.signal })
      .then(async (response) => { if (!response.ok) throw new Error("Unable to load recognition workspace."); return response.json() as Promise<Workspace>; })
      .then((data) => { setWorkspace(data); setStatus("ready"); })
      .catch((error: unknown) => { if ((error as Error).name !== "AbortError") setStatus("error"); });
    return () => controller.abort();
  }, [mode]);
  const state = ({
    blocked: { title: "Submission blocked", detail: "A blocking requirement is unresolved. No packet or delivery may be claimed.", badge: "Stop", tone: "stop" },
    confirmed: { title: "Human-confirmed version", detail: "Exact artifacts, playbook, profile, mappings, caveats, and requested action are pinned.", badge: "Ready to deliver", tone: "warn" },
    delivered: { title: "Delivery evidenced", detail: "A receipt proves custody of exact bytes. It does not prove review or acceptance.", badge: "Receipt recorded", tone: "pass" },
    clarification: { title: "Clarification answered", detail: "Original correspondence and normalized reason remain separate; cited evidence stays version-pinned.", badge: "Response preserved", tone: "pass" },
    accepted: { title: "Evidence accepted", detail: "A human-recorded external disposition is preserved without inferring rating or placement outcomes.", badge: "Evidence only", tone: "pass" },
    corrected: { title: "Correction appended", detail: "A successor event corrects the record without overwriting the original response.", badge: "History intact", tone: "warn" },
    pending: { title: "Cycle closed, outcome pending", detail: "Evidence review ended while rating and placement remained unknown. Missing results stay missing.", badge: "Pending explicit", tone: "neutral" },
    revoked: { title: "Reviewer access revoked", detail: "The scoped link no longer opens and cannot expose other cases or later submission versions.", badge: "Access closed", tone: "stop" },
  } as const)[scenario];
  if (status === "loading") return <section className="market-recognition-state"><LoaderCircle className="spin"/><h1>Loading market recognition</h1><p>Reading submission hashes, delivery receipts, reviewer scope, correspondence, and outcome ledgers.</p></section>;
  if (status === "error") return <section className="market-recognition-state error"><AlertTriangle/><h1>Market recognition unavailable</h1><p>No delivery, acceptance, rating, underwriting, placement, or funding result was inferred.</p><button className="button primary" onClick={() => location.reload()}>Retry</button></section>;
  if (!workspace || !workspace.bindings.length) return <section className="market-recognition-state"><Inbox/><h1>No recognition submission</h1><p>Prepare a human-confirmed, version-pinned evidence package before opening market review.</p></section>;
  const binding = workspace.bindings[0], delivery = workspace.deliveries[0], receipt = workspace.receipts[0], session = workspace.sessions[0], request = workspace.requests[0], response = workspace.requestResponses[0];
  const chooseTab = (next: Tab) => { setTab(next); setNotice(`${label(next)} view opened.`); };
  return <div className="market-recognition" data-testid="market-recognition-workspace">
    <header className="market-recognition-hero"><div><span className="eyebrow">M9 · submissions, review & outcomes</span><h1>Deliver exact evidence. Preserve the market’s exact answer.</h1><p>Version-pinned submissions, scoped review, immutable correspondence, and separated evidence, model, rating, underwriting, placement, and funding outcomes.</p></div><div className="market-recognition-seal"><Fingerprint/><span>Manifest verified</span><strong>{shortened("7f2215d44dfa6f8e")}</strong><small>Exact bytes · SHA-256</small></div></header>
    <section className="market-recognition-boundary"><ShieldAlert/><div><strong>Recognition is recorded, never predicted</strong><span>Delivery is not acceptance. Evidence acceptance is not pricing, capacity, renewal, funding, compliance, or risk certification.</span></div><b>{mode === "sandbox" ? "Fictional market" : "Production tenant"}</b></section>
    <section className={`market-recognition-gate ${state.tone}`} aria-live="polite"><div>{state.tone === "pass" ? <CheckCircle2/> : state.tone === "stop" ? <XCircle/> : <Clock3/>}<div><span>Controlled lifecycle</span><strong>{state.title}</strong><p>{state.detail}</p></div></div><label><span>{state.badge}</span><select aria-label="Inspect recognition scenario" value={scenario} onChange={(event) => setScenario(event.target.value as Scenario)}><option value="blocked">Blocked</option><option value="confirmed">Confirmed</option><option value="delivered">Delivered</option><option value="clarification">Clarification</option><option value="accepted">Evidence accepted</option><option value="corrected">Corrected</option><option value="pending">Outcome pending</option><option value="revoked">Access revoked</option></select></label></section>
    <div className="market-recognition-metrics"><div><FileKey2/><span>Submission version</span><strong>v3 · immutable</strong></div><div><Send/><span>Delivery</span><strong>{scenario === "blocked" || scenario === "confirmed" ? "Not claimed" : "Receipt verified"}</strong></div><div><LockKeyhole/><span>Reviewer scope</span><strong>{scenario === "revoked" ? "Revoked" : "1 case · 1 version"}</strong></div><div><FileCheck2/><span>Downstream outcomes</span><strong>{scenario === "pending" ? "2 pending" : "Recorded separately"}</strong></div></div>
    <nav className="market-recognition-tabs" aria-label="Market recognition views"><button className={tab === "submission" ? "active" : ""} aria-pressed={tab === "submission"} onClick={() => chooseTab("submission")}><Send/>Submission</button><button className={tab === "reviewer" ? "active" : ""} aria-pressed={tab === "reviewer"} onClick={() => chooseTab("reviewer")}><LockKeyhole/>Secure reviewer</button><button className={tab === "decisions" ? "active" : ""} aria-pressed={tab === "decisions"} onClick={() => chooseTab("decisions")}><BadgeCheck/>Decisions</button><button className={tab === "maintenance" ? "active" : ""} aria-pressed={tab === "maintenance"} onClick={() => chooseTab("maintenance")}><RefreshCw/>Maintenance</button></nav>
    {tab === "submission" ? <section className="market-recognition-grid"><article className="market-recognition-panel"><span className="eyebrow">Pinned submission</span><h2>{String(binding.destinationLabel)}</h2><p>{String(binding.requestedAction)}</p><dl><div><dt>Submission</dt><dd>{String(binding.submissionVersionId)}</dd></div><div><dt>Playbook</dt><dd>{String(binding.playbookVersionId)}</dd></div><div><dt>Target profile</dt><dd>{String(binding.profileVersionId)}</dd></div><div><dt>Commitment</dt><dd>{String(binding.commitmentVersionId)}</dd></div></dl><div className="market-recognition-caveat"><ShieldAlert/><span>{(binding.caveatSnapshot as string[])[1]}</span></div></article><article className="market-recognition-panel"><span className="eyebrow">Delivery custody</span><h2>Attempts never disappear</h2><div className="delivery-attempt failed"><XCircle/><div><b>Attempt 1 · failed</b><span>Provider unavailable · no delivery claimed</span></div></div><div className="delivery-attempt delivered"><CheckCircle2/><div><b>Attempt {String(delivery.attemptNumber)} · delivered</b><span>{String(delivery.providerReference)} · {String(delivery.deliveredAt)}</span></div></div><div className="receipt-hash"><Fingerprint/><div><span>Receipt hash</span><code>{String(receipt.receiptHash)}</code><small>{String(receipt.sourceAuthority)}</small></div></div><button className="button" aria-expanded={detailsOpen} onClick={() => { setDetailsOpen((value) => !value); setNotice(detailsOpen ? "Receipt details closed." : "Receipt details opened."); }}>{detailsOpen ? "Hide receipt chain" : "Inspect receipt chain"}</button>{detailsOpen ? <p className="market-recognition-detail">Request {shortened(delivery.requestHash)}… → provider reference → immutable receipt {shortened(receipt.receiptHash)}… Exact-byte readback passed; recipient acceptance remains unclaimed.</p> : null}</article></section> : null}
    {tab === "reviewer" ? <section className="market-recognition-grid"><article className="market-recognition-panel"><div className="market-recognition-panel-head"><div><span className="eyebrow">Isolated reviewer session</span><h2>{scenario === "revoked" ? "Access revoked" : "Active until 19 Dec"}</h2></div>{scenario === "revoked" ? <XCircle/> : <KeyRound/>}</div><dl><div><dt>Version</dt><dd>{String(session.submissionVersionId)}</dd></div><div><dt>Downloads</dt><dd>{session.downloadAllowed ? "Allowed" : "Disabled"}</dd></div><div><dt>Scope</dt><dd>Read + clarification + evidence response</dd></div><div><dt>Cross-case access</dt><dd>Denied</dd></div></dl><button className="button danger" onClick={() => { setScenario("revoked"); setNotice("Reviewer access revoked in this scenario."); }}>Revoke access</button></article><article className="market-recognition-panel"><span className="eyebrow">Clarification thread</span><h2>Original language retained</h2><div className="correspondence"><MessageSquareText/><div><span>Reviewer · {label(String(request.normalizedReason))}</span><blockquote>{String(request.originalLanguage)}</blockquote></div></div><div className="correspondence response"><ShieldCheck/><div><span>Broker · human confirmed</span><blockquote>{String(response.originalLanguage)}</blockquote><small>Evidence: {(response.evidenceVersionIds as string[]).join(" · ")}</small></div></div></article></section> : null}
    {tab === "decisions" ? <section className="market-recognition-grid"><article className="market-recognition-panel decision-ledger"><span className="eyebrow">Separated response ledgers</span><h2>No category fills another</h2>{[["Evidence", "accepted", "Externally recorded"], ["Model input", "input modified", "Accepted value separate"], ["Rating", "unknown", "No determination supplied"], ["Underwriting", "quote review initiated", "Review only"], ["Placement", "not recorded", "Explicitly unavailable"], ["Funding", "not recorded", "Reviewer cannot write"]].map(([name, value, note]) => <div key={name}><span>{name}</span><strong>{label(value)}</strong><small>{note}</small></div>)}</article><article className="market-recognition-panel"><span className="eyebrow">Correction history</span><h2>Original → successor</h2><div className="correction-chain"><div><span>Original event</span><strong>Clarification required</strong><small>Scope could not be determined from E07 v1.</small></div><ArchiveRestore/><div><span>Correcting event</span><strong>Accepted</strong><small>E07 v2 scoped to Buildings 4 and 5. Original remains.</small></div></div><button className="button" onClick={() => { setScenario("corrected"); setNotice("Correction lineage highlighted."); }}>Highlight correction</button></article></section> : null}
    {tab === "maintenance" ? <section className="market-recognition-grid"><article className="market-recognition-panel"><span className="eyebrow">Case closure</span><h2>Closed · outcome pending</h2><p>{String(workspace.closures[0]?.note)}</p><div className="pending-list"><span><Clock3/>Rating treatment not provided</span><span><Clock3/>Placement response pending</span></div></article><article className="market-recognition-panel"><span className="eyebrow">Next renewal cycle</span><h2>Maintenance does not silently carry</h2><div className="maintenance-roll"><RefreshCw/><div><span>{label(String(workspace.rollForwards[0]?.status))}</span><strong>Roof-image refresh</strong><p>{String(workspace.rollForwards[0]?.basis)}</p></div></div><button className="button" onClick={() => setNotice("Maintenance review queued; no evidence was auto-approved.")}>Queue human review</button></article></section> : null}
    <p className="sr-only" aria-live="polite">{notice}</p>
    <footer className="market-recognition-footer"><ShieldCheck/><strong>Evidence readiness only.</strong><span>No wildfire score · no inferred compliance · no promised insurance, pricing, funding, capacity, renewal, or acceptance.</span></footer>
  </div>;
}
