"use client";

import { AlertTriangle, ArrowRight, BadgeCheck, BarChart3, Building2, CheckCircle2, Clock3, Database, Download, FileBarChart, Fingerprint, GitBranch, Inbox, LoaderCircle, LockKeyhole, Network, ShieldCheck, UsersRound, XCircle } from "lucide-react";
import { useEffect, useState } from "react";

type Tab = "programme" | "graph" | "analytics" | "rights";
type Scenario = "active" | "insufficient" | "maintenance" | "privacy_blocked";
type Workspace = {
  cohorts: Array<Record<string, unknown>>; versions: Array<Record<string, unknown>>; memberships: Array<Record<string, unknown>>;
  policies: Array<Record<string, unknown>>; reviews: Array<Record<string, unknown>>; publications: Array<Record<string, unknown>>;
  graphEvents: Array<Record<string, unknown>>; baselines: Array<Record<string, unknown>>; snapshots: Array<Record<string, unknown>>;
  reports: Array<Record<string, unknown>>; artifacts: Array<Record<string, unknown>>; receipts: Array<Record<string, unknown>>;
  benefits: Array<Record<string, unknown>>;
  boundaries: { scope: string; crossCustomerAggregation: string; predictiveAcceptance: boolean; premiumAttribution: boolean; causalLossReduction: boolean };
};

const fixture: Workspace = {
  cohorts: [{ id: "cohort-fixture", canonicalKey: "cal-community-2027", name: "California community resilience cohort", sponsorName: "Fictional California Resilience Partnership", description: "Fictional multi-property administrative cohort for governed workflow evaluation." }],
  versions: [{ id: "cohort-v1", versionNumber: 1, programmeVersionId: "programme-v3", profileVersionId: "profile-community-v4", geography: "California WUI communities · fixture", propertyClass: "community association", state: "active", methodologyVersion: "fortify-programme-cohort-1", limitations: "Administrative fixture only; eligibility and programme outcomes are non-predictive." }],
  memberships: [
    { id: "member-1", propertyId: "property-cedar", name: "Cedar Ridge Commons", county: "Marin", eventType: "project_started", reason: "Published programme rules matched the confirmed property record.", project: "Shared-edge envelope programme", occurredAt: "2026-11-08T18:00:00.000Z" },
    { id: "member-2", propertyId: "property-sierra", name: "Sierra Terrace HOA", county: "Sonoma", eventType: "qualified", reason: "Deterministic rule evaluation is eligible; no award is implied.", project: "Evidence scope under review", occurredAt: "2026-11-10T18:00:00.000Z" },
    { id: "member-3", propertyId: "property-madrone", name: "Madrone Court", county: "Napa", eventType: "insufficient_evidence", reason: "Building schedule and affordability evidence are unavailable.", project: "No project created", occurredAt: "2026-11-11T18:00:00.000Z" },
  ],
  policies: [
    { id: "policy-tenant-v2", versionNumber: 2, mode: "tenant_only", status: "published", minimumCohortSize: 10, suppressionThreshold: 10, deidentificationMethod: "Tenant-isolated identifiers; no cross-customer join", retentionDays: 365, deletionTreatment: "Rebuild snapshots after governed deletion." },
    { id: "policy-cross-draft", versionNumber: 3, mode: "cross_customer_opt_in", status: "draft", minimumCohortSize: 20, suppressionThreshold: 10, deidentificationMethod: "Pending contractual and privacy review", retentionDays: 180, deletionTreatment: "Unavailable until contract and opt-in are recorded." },
  ],
  reviews: [{ policyVersionId: "policy-tenant-v2", decision: "approved", rightsChecked: true, privacyChecked: true, reviewerSubject: "privacy-reviewer@fixture.test" }],
  publications: [{ policyVersionId: "policy-tenant-v2", decision: "published", publisherSubject: "programme-publisher@fixture.test" }],
  graphEvents: [
    { id: "graph-1", eventType: "profile_selected", subjectType: "baseline_assessment", subjectId: "baseline-v2", relationship: "evaluated_against", objectType: "target_profile_version", objectId: "profile-community-v4", occurredAt: "2026-10-12T16:00:00.000Z", evidenceLevel: "physical_specification" },
    { id: "graph-2", eventType: "funding_approved", subjectType: "funding_commitment_event", subjectId: "commitment-approved-v2", relationship: "funds", objectType: "resilience_project", objectId: "project-edge-v3", occurredAt: "2026-10-22T16:00:00.000Z", evidenceLevel: "financing_or_programme_treatment" },
    { id: "graph-3", eventType: "installation_verified", subjectType: "verification_finding", subjectId: "finding-roof-v2", relationship: "supports", objectType: "model_input_mapping", objectId: "mapping-roof-v2", occurredAt: "2026-11-26T16:00:00.000Z", evidenceLevel: "verified_installation" },
    { id: "graph-4", eventType: "submission_delivered", subjectType: "submission_delivery", subjectId: "delivery-v2", relationship: "delivered_version", objectType: "submission_version", objectId: "submission-v3", occurredAt: "2026-12-12T18:20:00.000Z" },
    { id: "graph-5", eventType: "evidence_accepted", subjectType: "evidence_acceptance_event", subjectId: "evidence-response-v2", relationship: "records_response_for", objectType: "evidence_version", objectId: "evidence-roof-e07-v2", occurredAt: "2026-12-14T16:00:00.000Z", evidenceLevel: "underwriting_treatment" },
    { id: "graph-6", eventType: "maintenance_review_required", subjectType: "maintenance_roll_forward", subjectId: "roll-forward-v1", relationship: "carries_obligation_to", objectType: "renewal_case", objectId: "renewal-2028", occurredAt: "2026-12-18T16:00:00.000Z" },
  ],
  baselines: [{ id: "baseline-workflow-v1", baselineType: "brokerage_workflow", periodStart: "2026-01-01", periodEnd: "2026-06-30", caseCount: 18, manualMinutesPerCase: 540, manualTouchesPerCase: 31, externalCostCentsPerCase: 0, source: "Fictional design-partner interview", sourceVersion: "confirmed-2026-07", limitations: "Self-reported fixture baseline; not an observed customer result.", humanConfirmed: true }],
  snapshots: [{ id: "snapshot-v1", analyticsScope: "tenant_only", methodologyVersion: "fortify-descriptive-analytics-1", metrics: { applicants: 3, qualifiedProperties: 2, projectsStarted: 1, projectsCompleted: 0, eligibleAssessments: 2, verifiedFindings: 1, marketSubmissions: 1, deliveredSubmissions: 1, evidenceAccepted: 1, modelMappingsAccepted: 1, ratingTreatmentsRecorded: 0, underwritingResponses: 1, placementResponses: 0, maintenanceRollForwards: 1, projectCostCents: 16800000, fundingContributionCents: 7400000, averageCaseToDeliveryHours: 146.5, averageMarketReviewHours: 45.75, workflowManualTouches: 27 }, denominators: { qualifiedProperties: 3, projectsCompleted: 1, evidenceAccepted: 1, deliveredSubmissions: 1, maintenanceRollForwards: 1 }, caveats: ["Tenant-only descriptive analytics.", "No causal or predictive claim."] }],
  reports: [{ id: "report-roi", reportType: "brokerage_roi", title: "Brokerage workflow value report", interpretationBoundary: "Baseline and observed measures are separate; no premium, claims, causal savings, or return is attributed to Fortify." }, { id: "report-programme", reportType: "programme_outcome", title: "Programme outcome report", interpretationBoundary: "Descriptive counts do not prove programme effectiveness or caused loss reduction." }],
  artifacts: [{ reportId: "report-roi", format: "json", sha256: "8d4bd710b76c1cb784b77a8774b167e10316eea6987d66044d7262eb845f407f", sizeBytes: 2831 }, { reportId: "report-roi", format: "csv", sha256: "788e9536d3fb54d24d39089899c291a90621645866ccadf394442e3bfa5f0fa7", sizeBytes: 1244 }, { reportId: "report-programme", format: "json", sha256: "a9764cbd0c0ff8e8b7ae8778c0eb74113f61ca397ac12c93cac1766fe7d0c383", sizeBytes: 2410 }],
  receipts: [{ id: "query-receipt-v1", requestedScope: "tenant_only", distinctTenantCount: 1, distinctPropertyCount: 3, suppressionApplied: false, payloadHash: "94f358dfe07d9d824b7a1f845e40d6bbeb96cebdc8fbe29c22c9c318621f15da" }],
  benefits: [{ stakeholderName: "Cedar Ridge Commons", stakeholderType: "property_owner", expectedBenefitCategory: "Evidence collection workflow", expectedCostCents: 16800000, fundingContributionCents: 7400000, evidenceLevel: "documented", realisedResponseState: "not_observed", uncertainty: "Insurance and financial response remain unknown." }],
  boundaries: { scope: "tenant_only", crossCustomerAggregation: "disabled_without_separate_authority", predictiveAcceptance: false, premiumAttribution: false, causalLossReduction: false },
};

const label = (value: unknown) => String(value ?? "Unavailable").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const metricLabel: Record<string, string> = { applicants: "Applicants", qualifiedProperties: "Qualified properties", projectsStarted: "Projects started", projectsCompleted: "Projects completed", verifiedFindings: "Approved findings", deliveredSubmissions: "Delivered submissions", evidenceAccepted: "Evidence accepted", underwritingResponses: "Underwriting responses", maintenanceRollForwards: "Maintenance roll-forwards", averageCaseToDeliveryHours: "Case → delivery", averageMarketReviewHours: "Delivery → response" };

export function ProgrammeAnalyticsWorkspace({ mode }: { mode: "sandbox" | "production" }) {
  const [workspace, setWorkspace] = useState<Workspace | null>(mode === "sandbox" ? fixture : null);
  const [status, setStatus] = useState<"loading" | "ready" | "error">(mode === "sandbox" ? "ready" : "loading");
  const [tab, setTab] = useState<Tab>("programme"); const [scenario, setScenario] = useState<Scenario>("active");
  const [selectedPropertyId, setSelectedPropertyId] = useState("property-cedar"); const [reportOpen, setReportOpen] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => {
    if (mode !== "production") return;
    const controller = new AbortController();
    fetch("/api/production/programme-analytics/workspace", { cache: "no-store", signal: controller.signal })
      .then(async (response) => { if (!response.ok) throw new Error("Unable to load programme analytics."); return response.json() as Promise<Workspace>; })
      .then((data) => { setWorkspace(data); setStatus("ready"); })
      .catch((error: unknown) => { if ((error as Error).name !== "AbortError") setStatus("error"); });
    return () => controller.abort();
  }, [mode]);
  if (status === "loading") return <section className="programme-state"><LoaderCircle className="spin"/><h1>Loading programme intelligence</h1><p>Reading cohort scope, governed graph events, tenant metrics, baselines, and report receipts.</p></section>;
  if (status === "error") return <section className="programme-state error"><AlertTriangle/><h1>Programme intelligence unavailable</h1><p>No aggregate, ROI, insurance, or impact result was inferred.</p><button className="button primary" onClick={() => location.reload()}>Retry</button></section>;
  if (!workspace || !workspace.cohorts.length) return <section className="programme-state"><Inbox/><h1>No programme cohort</h1><p>Activate a source-pinned programme cohort before generating tenant-only descriptive analytics.</p></section>;
  const cohort = workspace.cohorts[0], version = workspace.versions[0], snapshot = workspace.snapshots[0]; const metrics = (snapshot?.metrics ?? {}) as Record<string, number | null>;
  const selected = workspace.memberships.find((item) => item.propertyId === selectedPropertyId) ?? workspace.memberships[0];
  const state = ({ active: { tone: "pass", icon: CheckCircle2, title: "Cohort active", detail: "Exact programme and profile versions are pinned; membership decisions remain append-only." }, insufficient: { tone: "warn", icon: AlertTriangle, title: "Evidence insufficient", detail: "One applicant lacks a building schedule and affordability evidence. It is not counted as qualified." }, maintenance: { tone: "warn", icon: Clock3, title: "Maintenance review due", detail: "A roll-forward exists, but evidence is not silently treated as current for the next renewal." }, privacy_blocked: { tone: "stop", icon: LockKeyhole, title: "Cross-customer query blocked", detail: "A draft opt-in policy is not cross-tenant authority. No benchmark or customer-identifiable aggregate ran." } } as const)[scenario];
  const StateIcon = state.icon; const chooseTab = (next: Tab) => { setTab(next); setNotice(`${label(next)} view opened.`); };
  const downloadFixture = (format: "json" | "csv") => { const body = format === "json" ? JSON.stringify({ report: workspace.reports[0], snapshot }, null, 2) : Object.entries(metrics).map(([key, value]) => `${key},${value ?? "unavailable"}`).join("\n"); const url = URL.createObjectURL(new Blob([body], { type: format === "json" ? "application/json" : "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `fortify-fixture-brokerage-report.${format}`; anchor.click(); URL.revokeObjectURL(url); setNotice(`${format.toUpperCase()} fixture report exported.`); };
  return <div className="programme-analytics" data-testid="programme-analytics-workspace">
    <header className="programme-hero"><div><span className="eyebrow">M10 · programme administration & intelligence</span><h1>See the programme. Trace every conclusion.</h1><p>Versioned cohorts, governed recognition events, tenant-only descriptive analytics, and exact exportable reports—with privacy and attribution boundaries kept visible.</p></div><div className="programme-hero-mark"><Network/><span>Recognition graph</span><strong>{workspace.graphEvents.length} governed events</strong><small>1 tenant · no benchmark</small></div></header>
    <section className="programme-boundary"><ShieldCheck/><div><strong>Descriptive operations evidence—not an impact model</strong><span>No predicted acceptance, premium attribution, caused loss reduction, cross-customer training, or hidden composite ROI.</span></div><b>{mode === "sandbox" ? "Fictional programme" : "Production tenant"}</b></section>
    <section className={`programme-gate ${state.tone}`} aria-live="polite"><div><StateIcon/><div><span>Controlled scenario</span><strong>{state.title}</strong><p>{state.detail}</p></div></div><label><span>{scenario === "privacy_blocked" ? "Fail closed" : "Inspect state"}</span><select aria-label="Inspect programme scenario" value={scenario} onChange={(event) => setScenario(event.target.value as Scenario)}><option value="active">Active cohort</option><option value="insufficient">Insufficient evidence</option><option value="maintenance">Maintenance due</option><option value="privacy_blocked">Privacy blocked</option></select></label></section>
    <section className="programme-metrics"><div><UsersRound/><span>Applicants</span><strong>{metrics.applicants ?? "—"}</strong><small>{metrics.qualifiedProperties ?? 0} qualified</small></div><div><Building2/><span>Projects</span><strong>{metrics.projectsStarted ?? "—"} started</strong><small>{metrics.projectsCompleted ?? 0} completed</small></div><div><BadgeCheck/><span>Market evidence</span><strong>{metrics.evidenceAccepted ?? "—"} accepted</strong><small>{metrics.ratingTreatmentsRecorded ?? 0} rating treatments</small></div><div><Clock3/><span>Case → delivery</span><strong>{metrics.averageCaseToDeliveryHours ?? "—"}h</strong><small>elapsed, not labour saved</small></div></section>
    <nav className="programme-tabs" aria-label="Programme analytics views"><button className={tab === "programme" ? "active" : ""} aria-pressed={tab === "programme"} onClick={() => chooseTab("programme")}><UsersRound/>Programme</button><button className={tab === "graph" ? "active" : ""} aria-pressed={tab === "graph"} onClick={() => chooseTab("graph")}><GitBranch/>Recognition graph</button><button className={tab === "analytics" ? "active" : ""} aria-pressed={tab === "analytics"} onClick={() => chooseTab("analytics")}><BarChart3/>Analytics & reports</button><button className={tab === "rights" ? "active" : ""} aria-pressed={tab === "rights"} onClick={() => chooseTab("rights")}><LockKeyhole/>Rights & privacy</button></nav>
    {tab === "programme" ? <section className="programme-layout"><article className="programme-panel cohort-summary"><div className="programme-panel-head"><div><span className="eyebrow">Active cohort · v{String(version.versionNumber)}</span><h2>{String(cohort.name)}</h2></div><BadgeCheck/></div><p>{String(cohort.description)}</p><dl><div><dt>Sponsor</dt><dd>{String(cohort.sponsorName)}</dd></div><div><dt>Geography</dt><dd>{String(version.geography)}</dd></div><div><dt>Programme</dt><dd>{String(version.programmeVersionId)}</dd></div><div><dt>Profile</dt><dd>{String(version.profileVersionId)}</dd></div></dl><div className="programme-caveat"><AlertTriangle/><span>{String(version.limitations)}</span></div></article><aside className="programme-member-list"><span className="eyebrow">Applicant ledger</span><h2>Latest decision, full history retained</h2>{workspace.memberships.map((item) => <button key={String(item.id)} className={selectedPropertyId === item.propertyId ? "active" : ""} onClick={() => { setSelectedPropertyId(String(item.propertyId)); setScenario(item.eventType === "insufficient_evidence" ? "insufficient" : "active"); }}><div><strong>{String(item.name)}</strong><span>{String(item.county)} County</span></div><b>{label(item.eventType)}</b></button>)}</aside><article className="programme-panel member-detail"><span className="eyebrow">Selected applicant</span><h2>{String(selected.name)}</h2><div className={`member-decision ${String(selected.eventType)}`}><Database/><div><span>{label(selected.eventType)}</span><strong>{String(selected.project)}</strong><p>{String(selected.reason)}</p></div></div><button className="button" onClick={() => setNotice("Exact membership source and append-only decision lineage opened.")}>Inspect decision lineage</button></article></section> : null}
    {tab === "graph" ? <section className="graph-workspace"><article className="programme-panel graph-map"><div className="programme-panel-head"><div><span className="eyebrow">Governed relationship map</span><h2>Physical change → external response</h2></div><Network/></div><div className="graph-chain"><div><span>Physical</span><strong>Profile v4</strong><small>Specification</small></div><ArrowRight/><div><span>Project</span><strong>Edge envelope</strong><small>Funding recorded</small></div><ArrowRight/><div><span>Verification</span><strong>Finding v2</strong><small>Installation verified</small></div><ArrowRight/><div><span>Market</span><strong>Submission v3</strong><small>Delivery evidenced</small></div><ArrowRight/><div><span>Outcome</span><strong>Evidence accepted</strong><small>Rating unknown</small></div></div><p className="graph-boundary">Every edge derives from an exact same-tenant audit event. A graph edge records provenance; it does not create recognition or causality.</p></article><article className="programme-panel graph-ledger"><span className="eyebrow">Append-only event ledger</span><h2>{workspace.graphEvents.length} traceable relations</h2>{workspace.graphEvents.map((event) => <div key={String(event.id)}><Fingerprint/><div><span>{label(event.eventType)} · {event.evidenceLevel ? label(event.evidenceLevel) : "No evidence-level claim"}</span><strong>{String(event.subjectType)} <ArrowRight/> {String(event.objectType)}</strong><code>{String(event.subjectId)} → {String(event.objectId)}</code></div></div>)}</article></section> : null}
    {tab === "analytics" ? <section className="analytics-layout"><article className="programme-panel metric-register"><div className="programme-panel-head"><div><span className="eyebrow">Tenant-only snapshot</span><h2>Measures with denominators</h2></div><BarChart3/></div>{Object.keys(metricLabel).map((key) => { const value = metrics[key]; return <div key={key}><span>{metricLabel[key]}</span><strong>{value === null || value === undefined ? "Unavailable" : key.endsWith("Hours") ? `${value}h` : value}</strong><small>{((snapshot?.denominators ?? {}) as Record<string, number>)[key] ? `n=${((snapshot?.denominators ?? {}) as Record<string, number>)[key]}` : "direct governed count"}</small></div>; })}</article><article className="programme-panel report-register"><span className="eyebrow">Exact exports</span><h2>Brokerage and sponsor reports</h2>{workspace.reports.map((report) => <div className="report-row" key={String(report.id)}><FileBarChart/><div><span>{label(report.reportType)}</span><strong>{String(report.title)}</strong><p>{String(report.interpretationBoundary)}</p></div><button className="button" onClick={() => { setReportOpen(true); setNotice(`${String(report.title)} preview opened.`); }}>Preview</button></div>)}{reportOpen ? <div className="report-preview"><div><strong>Customer-confirmed baseline</strong><span>18 cases · 540 self-reported manual minutes/case · 31 manual touches</span></div><div><strong>Observed tenant snapshot</strong><span>27 governed workflow events · 146.5 elapsed hours to delivery</span></div><p>These measures are not interchangeable. No labour saving, financial return, premium effect, or claims impact is inferred.</p><div><button className="button" onClick={() => downloadFixture("json")}><Download/>JSON</button><button className="button" onClick={() => downloadFixture("csv")}><Download/>CSV</button></div></div> : null}</article></section> : null}
    {tab === "rights" ? <section className="rights-layout"><article className="programme-panel"><div className="programme-panel-head"><div><span className="eyebrow">Published policy · v{String(workspace.policies[0]?.versionNumber)}</span><h2>Tenant-only by default</h2></div><LockKeyhole/></div><dl><div><dt>Scope</dt><dd>{label(workspace.policies[0]?.mode)}</dd></div><div><dt>Minimum cohort</dt><dd>{String(workspace.policies[0]?.minimumCohortSize)}</dd></div><div><dt>Suppression floor</dt><dd>{String(workspace.policies[0]?.suppressionThreshold)}</dd></div><div><dt>Retention</dt><dd>{String(workspace.policies[0]?.retentionDays)} days</dd></div></dl><p>{String(workspace.policies[0]?.deidentificationMethod)}</p><div className="rights-signoff"><CheckCircle2/><span>Author, privacy/rights reviewer, and publisher are separate fixture humans.</span></div></article><article className="programme-panel privacy-stop"><XCircle/><span className="eyebrow">Cross-customer boundary</span><h2>Not authorized</h2><p>A draft policy, contractual reference, opt-in checkbox, or cohort threshold alone cannot give this tenant-scoped service authority over another customer’s records.</p><ul><li>Explicit contractual permission required</li><li>Opt-in and deletion treatment required</li><li>Minimum cohort and suppression required</li><li>Separate cross-tenant execution authority not implemented</li></ul><button className="button danger" onClick={() => { setScenario("privacy_blocked"); setNotice("Cross-customer query denied; no aggregate executed."); }}>Test blocked aggregate</button></article><article className="programme-panel query-receipt"><Fingerprint/><div><span className="eyebrow">Exact query receipt</span><h2>1 tenant · 3 properties</h2><code>{String(workspace.receipts[0]?.payloadHash)}</code><p>Scope `tenant_only` · suppression not required · predictive model false.</p></div></article></section> : null}
    <p className="sr-only" aria-live="polite">{notice}</p><footer className="programme-footer"><ShieldCheck/><strong>Governed description only.</strong><span>No risk score · no predicted acceptance · no premium attribution · no causal loss-reduction or programme-effectiveness claim.</span></footer>
  </div>;
}
